apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cce-prod

resources:
  - ../../base
  - namespace.yaml

configMapGenerator:
  - name: cce-config
    literals:
      - POSTGRES_DB=ccedb
      - POSTGRES_HOST=${VM_HOST_IP}
      - POSTGRES_PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS=${VM_HOST_IP}:9092
      - KAFKA_UI_CLUSTER_NAME=cce-prod
      - OPENHIM_CORE_HOST=197.243.24.138
      - KEYCLOAK_HOST=

secretGenerator:
  - name: cce-secrets
    literals:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=CHANGE_ME_PROD
      - CCE_COLLECTOR_AUTH_TOKEN=CHANGE_ME_PROD
      - GRAFANA_ADMIN_USER=admin
      - GRAFANA_ADMIN_PASSWORD=CHANGE_ME_PROD
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=CHANGE_ME_PROD
      - OPENHIM_USERNAME=CHANGE_ME_PROD
      - OPENHIM_PASSWORD=CHANGE_ME_PROD
      - KEYCLOAK_CLIENT_ID=CHANGE_ME_PROD
      - KEYCLOAK_CLIENT_SECRET=CHANGE_ME_PROD

generatorOptions:
  disableNameSuffixHash: true

# PROD-specific patches — higher resources
patches:
  - target:
      kind: Deployment
      name: cce-compliance-service
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
  - target:
      kind: Deployment
      name: cce-collector-service
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m

# Use release images for PROD
images:
  - name: ghcr.io/openphc/openhim-cce-emitter-adaptor
    newTag: release-1.0.0
  - name: ghcr.io/openphc/cce-collector-service
    newTag: release-1.0.0
  - name: ghcr.io/openphc/cce-compliance-service
    newTag: release-1.0.0
  - name: ghcr.io/openphc/cce-scheduler-service
    newTag: demo
  - name: ghcr.io/openphc/cce-insights-service
    newTag: demo
  - name: ghcr.io/openphc/cce-insights-ui
    newTag: demo

commonLabels:
  environment: prod
