apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 9000
      defaultDatabase: cce_analytics
      username: cce_pipeline
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}

  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: cce-postgres:5432
    database: ccedb
    user: cce_cdc_user
    jsonData:
      sslmode: disable
    secureJsonData:
      password: ${CDC_PASSWORD}
