-- CCE Analytics ClickHouse Schema — Reference Table CDC Setup
-- Run: clickhouse-client --database cce_analytics < schema/08-reference-tables.sql
--
-- facility is owned by the matcher service (cce-matcher-service) in 2.0.0.
-- The table is defined in schema/01 and populated automatically via Debezium CDC:
--
--   PostgreSQL (matcher service)
--       V1__initial_schema.sql creates the table with REPLICA IDENTITY FULL
--       InboundEventConsumer inserts rows; programme staff set district_name /
--       expected_patients_per_day directly in SQL
--       ↓  Debezium CDC (WAL → Kafka)
--   Kafka topic: cce.public.facility
--       ↓  facility_queue + facility_mv (schema/02)
--   ClickHouse: facility (schema/01)
--
-- ONE-TIME SETUP (run on PostgreSQL before registering the updated connector):
--   ALTER PUBLICATION cce_analytics_pub ADD TABLE public.facility;
--
-- The Debezium connector (connectors/debezium-postgres-source.json) already includes
-- public.facility in table.include.list. On first connector start after the
-- publication is updated, Debezium performs an initial snapshot that seeds all existing
-- rows into ClickHouse, then streams live changes (INSERT/UPDATE/DELETE) going forward.
--
-- VERIFY CDC is flowing:
--   -- On ClickHouse: check rows arrived
--   SELECT count(), max(updated_at) FROM cce_analytics.facility FINAL;
--
--   -- On ClickHouse: check consumer lag (should be 0 after snapshot)
--   SELECT * FROM system.kafka_consumers WHERE database = 'cce_analytics';
--
-- No SQL in this file needs to be executed — the table DDL is in schema/01 and
-- the Kafka consumer objects are in schema/02.

USE cce_analytics;
