name: Deploy CCE Services

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select the environment to deploy"
        required: true
        type: choice
        options:
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: ${{ github.event.inputs.target_env }}

    steps:
      - name: Confirm environment input
        run: echo "Deploying to $TARGET_ENV"
        shell: bash

      - uses: actions/checkout@v6

      - name: Sync files to Dev Host
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -av --exclude='.git' --exclude='.github'
          path: ./
          remote_path: ${{ vars.DEV_REMOTE_PROJECT_PATH }}
          remote_host: ${{ secrets.DEV_HOST }}
          remote_user: ${{ secrets.DEV_USER }}
          remote_key: ${{ secrets.DEV_SSH_KEY }}
